// Vehicle details and photographs supplied by ARIVA. Prices are pending.
const catalogCars=[
 {
  "id": 6,
  "name": "Geely Xingyue L",
  "trim": "Cloudrise Edition",
  "type": "petrol",
  "fuel": "Бензин",
  "volume": "2.0 л",
  "horsepower": "238 л.с.",
  "power": "2.0 л",
  "drive": "FWD",
  "year": "2024",
  "mileage": 27000,
  "price": null,
  "image": "petrol/xingyue-l/01.webp",
  "photos": [
   "petrol/xingyue-l/01.webp",
   "petrol/xingyue-l/02.webp",
   "petrol/xingyue-l/03.webp",
   "petrol/xingyue-l/04.webp",
   "petrol/xingyue-l/05.webp",
   "petrol/xingyue-l/06.webp",
   "petrol/xingyue-l/07.webp",
   "petrol/xingyue-l/08.webp"
  ],
  "exteriorCount": 5
 },
 {
  "id": 7,
  "name": "Changan CS75 PLUS",
  "trim": "Premium",
  "type": "petrol",
  "fuel": "Бензин",
  "volume": "1.5 л",
  "horsepower": "188 л.с.",
  "power": "1.5 л",
  "drive": "FWD",
  "year": "2023",
  "mileage": 29600,
  "price": null,
  "image": "petrol/cs75-plus/01.webp",
  "photos": [
   "petrol/cs75-plus/01.webp",
   "petrol/cs75-plus/02.webp",
   "petrol/cs75-plus/03.webp",
   "petrol/cs75-plus/04.webp",
   "petrol/cs75-plus/05.webp",
   "petrol/cs75-plus/06.webp",
   "petrol/cs75-plus/07.webp",
   "petrol/cs75-plus/08.webp",
   "petrol/cs75-plus/09.webp"
  ],
  "exteriorCount": 5
 },
 {
  "id": 9,
  "name": "BMW X1",
  "trim": "sDrive25Li M Sport Package",
  "type": "petrol",
  "fuel": "Бензин",
  "volume": "2.0 л",
  "horsepower": "204 л.с.",
  "power": "2.0 л",
  "drive": "FWD",
  "year": "2023",
  "mileage": 60000,
  "price": null,
  "image": "petrol/bmw-x1/01.webp",
  "photos": [
   "petrol/bmw-x1/01.webp",
   "petrol/bmw-x1/02.webp",
   "petrol/bmw-x1/03.webp",
   "petrol/bmw-x1/04.webp",
   "petrol/bmw-x1/05.webp",
   "petrol/bmw-x1/06.webp",
   "petrol/bmw-x1/07.webp",
   "petrol/bmw-x1/08.webp"
  ],
  "exteriorCount": 5
 },
 {
  "id": 10,
  "name": "Audi Q3",
  "trim": "35 TFSI Fashion Dynamic",
  "type": "petrol",
  "fuel": "Бензин",
  "volume": "1.4 л",
  "horsepower": "150 л.с.",
  "power": "1.4 л",
  "drive": "FWD",
  "year": "2023",
  "mileage": 14000,
  "price": null,
  "image": "petrol/audi-q3/01.webp",
  "photos": [
   "petrol/audi-q3/01.webp",
   "petrol/audi-q3/02.webp",
   "petrol/audi-q3/03.webp",
   "petrol/audi-q3/04.webp",
   "petrol/audi-q3/05.webp",
   "petrol/audi-q3/06.webp",
   "petrol/audi-q3/07.webp",
   "petrol/audi-q3/08.webp"
  ],
  "exteriorCount": 5
 },
 {
  "id": 11,
  "name": "Toyota Camry",
  "trim": "S Knight Edition",
  "type": "petrol",
  "fuel": "Бензин",
  "volume": "2.0 л",
  "horsepower": "177 л.с.",
  "power": "2.0 л",
  "drive": "FWD",
  "year": "2023",
  "mileage": 20000,
  "price": null,
  "image": "petrol/camry/01.webp",
  "photos": [
   "petrol/camry/01.webp",
   "petrol/camry/02.webp",
   "petrol/camry/03.webp",
   "petrol/camry/04.webp",
   "petrol/camry/05.webp",
   "petrol/camry/06.webp",
   "petrol/camry/07.webp",
   "petrol/camry/08.webp",
   "petrol/camry/09.webp"
  ],
  "exteriorCount": 6
 },
 {
  "id": 12,
  "name": "Geely Boyue L",
  "trim": "Premium",
  "type": "petrol",
  "fuel": "Бензин",
  "volume": "1.5 л",
  "horsepower": "181 л.с.",
  "power": "1.5 л",
  "drive": "FWD",
  "year": "2023",
  "mileage": 20700,
  "price": null,
  "image": "petrol/boyue-l/01.webp",
  "photos": [
   "petrol/boyue-l/01.webp",
   "petrol/boyue-l/02.webp",
   "petrol/boyue-l/03.webp",
   "petrol/boyue-l/04.webp",
   "petrol/boyue-l/05.webp",
   "petrol/boyue-l/06.webp",
   "petrol/boyue-l/07.webp",
   "petrol/boyue-l/08.webp",
   "petrol/boyue-l/09.webp"
  ],
  "exteriorCount": 6
 },
 {
  "id": 13,
  "name": "Volkswagen Tiguan L",
  "trim": "",
  "type": "petrol",
  "fuel": "Бензин",
  "volume": "2.0 л",
  "horsepower": "186 л.с.",
  "power": "2.0 л",
  "drive": "FWD",
  "year": null,
  "mileage": 37000,
  "price": null,
  "image": "petrol/tiguan-l/01.webp",
  "photos": [
   "petrol/tiguan-l/01.webp",
   "petrol/tiguan-l/02.webp",
   "petrol/tiguan-l/03.webp",
   "petrol/tiguan-l/04.webp",
   "petrol/tiguan-l/05.webp",
   "petrol/tiguan-l/06.webp",
   "petrol/tiguan-l/07.webp",
   "petrol/tiguan-l/08.webp",
   "petrol/tiguan-l/09.webp"
  ],
  "exteriorCount": 6
 },
 {
  "id": 14,
  "name": "Geely Boyue Cool",
  "trim": "Smart Type",
  "type": "petrol",
  "fuel": "Бензин",
  "volume": "1.5 л",
  "horsepower": "181 л.с.",
  "power": "1.5 л",
  "drive": "FWD",
  "year": null,
  "mileage": 52000,
  "price": null,
  "image": "petrol/boyue-cool/01.webp",
  "photos": [
   "petrol/boyue-cool/01.webp",
   "petrol/boyue-cool/02.webp",
   "petrol/boyue-cool/03.webp",
   "petrol/boyue-cool/04.webp",
   "petrol/boyue-cool/05.webp",
   "petrol/boyue-cool/06.webp",
   "petrol/boyue-cool/07.webp",
   "petrol/boyue-cool/08.webp"
  ],
  "exteriorCount": 5
 },
 {
  "id": 1,
  "name": "BYD Sealion 06",
  "trim": "Voyage Edition",
  "type": "electric",
  "fuel": "Электро",
  "batteryCapacity": "82.73 кВт·ч",
  "rangeCltc": 710,
  "horsepower": "367 л.с.",
  "power": "82.73 кВт·ч",
  "drive": "RWD",
  "year": "2026",
  "mileage": 14000,
  "price": null,
  "image": "electric/sealion-06/01.webp",
  "photos": [
   "electric/sealion-06/01.webp",
   "electric/sealion-06/02.webp",
   "electric/sealion-06/03.webp",
   "electric/sealion-06/04.webp",
   "electric/sealion-06/05.webp",
   "electric/sealion-06/06.webp"
  ],
  "exteriorCount": 3
 },
 {
  "id": 2,
  "name": "Voyah Zhiyin",
  "trim": "Base",
  "type": "electric",
  "fuel": "Электро",
  "batteryCapacity": "81 кВт·ч",
  "rangeCltc": 600,
  "horsepower": "551 л.с.",
  "power": "81 кВт·ч",
  "drive": "AWD",
  "year": "2025",
  "mileage": 18000,
  "price": null,
  "image": "electric/voyah-zhiyin/01.webp",
  "photos": [
   "electric/voyah-zhiyin/01.webp",
   "electric/voyah-zhiyin/02.webp",
   "electric/voyah-zhiyin/03.webp",
   "electric/voyah-zhiyin/04.webp",
   "electric/voyah-zhiyin/05.webp",
   "electric/voyah-zhiyin/06.webp",
   "electric/voyah-zhiyin/07.webp",
   "electric/voyah-zhiyin/08.webp",
   "electric/voyah-zhiyin/09.webp"
  ],
  "exteriorCount": 4
 },
 {
  "id": 3,
  "name": "Geely Galaxy E5",
  "trim": "Explorer+ Edition",
  "type": "electric",
  "fuel": "Электро",
  "batteryCapacity": "68.39 кВт·ч",
  "rangeCltc": 610,
  "horsepower": "218 л.с.",
  "power": "68.39 кВт·ч",
  "drive": "FWD",
  "year": "2026",
  "mileage": 10000,
  "price": null,
  "image": "electric/galaxy-e5/01.webp",
  "photos": [
   "electric/galaxy-e5/01.webp",
   "electric/galaxy-e5/02.webp",
   "electric/galaxy-e5/03.webp",
   "electric/galaxy-e5/04.webp",
   "electric/galaxy-e5/05.webp",
   "electric/galaxy-e5/06.webp",
   "electric/galaxy-e5/07.webp",
   "electric/galaxy-e5/08.webp",
   "electric/galaxy-e5/09.webp",
   "electric/galaxy-e5/10.webp"
  ],
  "exteriorCount": 7
 },
 {
  "id": 4,
  "name": "Tesla Model Y",
  "trim": "",
  "type": "electric",
  "fuel": "Электро",
  "batteryCapacity": "62.5 кВт·ч",
  "rangeCltc": 593,
  "horsepower": "299 л.с.",
  "power": "62.5 кВт·ч",
  "drive": "RWD",
  "year": null,
  "mileage": 26600,
  "price": null,
  "image": "electric/tesla-model-y/01.webp",
  "photos": [
   "electric/tesla-model-y/01.webp",
   "electric/tesla-model-y/02.webp",
   "electric/tesla-model-y/03.webp",
   "electric/tesla-model-y/04.webp",
   "electric/tesla-model-y/05.webp",
   "electric/tesla-model-y/06.webp",
   "electric/tesla-model-y/07.webp",
   "electric/tesla-model-y/08.webp"
  ],
  "exteriorCount": 3
 },
 {
  "id": 15,
  "name": "BMW i3",
  "trim": "eDrive 35 L",
  "type": "electric",
  "fuel": "Электро",
  "batteryCapacity": "70 кВт·ч",
  "rangeCltc": 526,
  "horsepower": "286 л.с.",
  "power": "70 кВт·ч",
  "drive": "RWD",
  "year": "2025",
  "mileage": 100,
  "price": null,
  "image": "electric/bmw-i3/01.webp",
  "photos": [
   "electric/bmw-i3/01.webp",
   "electric/bmw-i3/02.webp",
   "electric/bmw-i3/03.webp",
   "electric/bmw-i3/04.webp",
   "electric/bmw-i3/05.webp",
   "electric/bmw-i3/06.webp",
   "electric/bmw-i3/07.webp",
   "electric/bmw-i3/08.webp",
   "electric/bmw-i3/09.webp",
   "electric/bmw-i3/10.webp"
  ],
  "exteriorCount": 6
 },
 {
  "id": 16,
  "name": "Zeekr 7X",
  "trim": "Smart Driving Edition",
  "type": "electric",
  "fuel": "Электро",
  "batteryCapacity": "100 кВт·ч",
  "rangeCltc": 780,
  "horsepower": "422 л.с.",
  "power": "100 кВт·ч",
  "drive": "RWD",
  "year": null,
  "mileage": 49000,
  "price": null,
  "image": "electric/zeekr-7x/01.webp",
  "photos": [
   "electric/zeekr-7x/01.webp",
   "electric/zeekr-7x/02.webp",
   "electric/zeekr-7x/03.webp",
   "electric/zeekr-7x/04.webp",
   "electric/zeekr-7x/05.webp",
   "electric/zeekr-7x/06.webp",
   "electric/zeekr-7x/07.webp",
   "electric/zeekr-7x/08.webp"
  ],
  "exteriorCount": 4
 },
 {
  "id": 17,
  "name": "Mercedes-Benz EQE",
  "trim": "Luxury Edition",
  "type": "electric",
  "fuel": "Электро",
  "batteryCapacity": "96.1 кВт·ч",
  "rangeCltc": 681,
  "horsepower": "408 л.с.",
  "power": "96.1 кВт·ч",
  "drive": "AWD",
  "year": "2025",
  "mileage": 9200,
  "price": null,
  "image": "electric/mercedes-eqe/01.webp",
  "photos": [
   "electric/mercedes-eqe/01.webp",
   "electric/mercedes-eqe/02.webp",
   "electric/mercedes-eqe/03.webp",
   "electric/mercedes-eqe/04.webp",
   "electric/mercedes-eqe/05.webp",
   "electric/mercedes-eqe/06.webp",
   "electric/mercedes-eqe/07.webp",
   "electric/mercedes-eqe/08.webp",
   "electric/mercedes-eqe/09.webp"
  ],
  "exteriorCount": 5
 },
 {
  "id": 18,
  "name": "Nissan N7",
  "trim": "510 Max",
  "type": "electric",
  "fuel": "Электро",
  "batteryCapacity": "58 кВт·ч",
  "rangeCltc": 510,
  "horsepower": "218 л.с.",
  "power": "58 кВт·ч",
  "drive": "FWD",
  "year": "2025",
  "mileage": 34700,
  "price": null,
  "image": "electric/nissan-n7/01.webp",
  "photos": [
   "electric/nissan-n7/01.webp",
   "electric/nissan-n7/02.webp",
   "electric/nissan-n7/03.webp",
   "electric/nissan-n7/04.webp",
   "electric/nissan-n7/05.webp",
   "electric/nissan-n7/06.webp",
   "electric/nissan-n7/07.webp",
   "electric/nissan-n7/08.webp",
   "electric/nissan-n7/09.webp",
   "electric/nissan-n7/10.webp"
  ],
  "exteriorCount": 7
 },
 {
  "id": 8,
  "name": "Li Auto L6",
  "trim": "PRO",
  "type": "hybrid",
  "fuel": "Гибрид",
  "batteryCapacity": "36.8 кВт·ч",
  "horsepower": "408 л.с.",
  "rangeCltc": 1390,
  "power": "36.8 кВт·ч",
  "drive": "AWD",
  "year": "2024",
  "mileage": null,
  "price": null,
  "image": "hybrid/li-l6/01.webp",
  "photos": [
   "hybrid/li-l6/01.webp",
   "hybrid/li-l6/02.webp",
   "hybrid/li-l6/03.webp",
   "hybrid/li-l6/04.webp",
   "hybrid/li-l6/05.webp",
   "hybrid/li-l6/06.webp",
   "hybrid/li-l6/07.webp",
   "hybrid/li-l6/08.webp",
   "hybrid/li-l6/09.webp",
   "hybrid/li-l6/10.webp"
  ],
  "exteriorCount": 6
 },
 {
  "id": 5,
  "name": "Volkswagen ID.ERA",
  "trim": "",
  "type": "hybrid",
  "fuel": "Гибрид",
  "batteryCapacity": "65.2 кВт·ч",
  "horsepower": "517 л.с.",
  "rangeCltc": 1651,
  "power": "65.2 кВт·ч",
  "drive": "AWD",
  "year": "2026",
  "mileage": null,
  "price": null,
  "image": "hybrid/vw-id-era/01.webp",
  "photos": [
   "hybrid/vw-id-era/01.webp",
   "hybrid/vw-id-era/02.webp",
   "hybrid/vw-id-era/03.webp",
   "hybrid/vw-id-era/04.webp",
   "hybrid/vw-id-era/05.webp",
   "hybrid/vw-id-era/06.webp",
   "hybrid/vw-id-era/07.webp",
   "hybrid/vw-id-era/08.webp"
  ],
  "exteriorCount": 6
 },
 {
  "id": 19,
  "name": "Deepal S09",
  "trim": "Ultra+ Haute Couture Edition",
  "type": "hybrid",
  "fuel": "Гибрид",
  "batteryCapacity": "40.18 кВт·ч",
  "horsepower": "493 л.с.",
  "rangeCltc": 1066,
  "power": "40.18 кВт·ч",
  "drive": "AWD",
  "year": "2025",
  "mileage": null,
  "price": null,
  "image": "hybrid/deepal-s09/01.webp",
  "photos": [
   "hybrid/deepal-s09/01.webp",
   "hybrid/deepal-s09/02.webp",
   "hybrid/deepal-s09/03.webp",
   "hybrid/deepal-s09/04.webp",
   "hybrid/deepal-s09/05.webp",
   "hybrid/deepal-s09/06.webp",
   "hybrid/deepal-s09/07.webp",
   "hybrid/deepal-s09/08.webp",
   "hybrid/deepal-s09/09.webp"
  ],
  "exteriorCount": 6
 },
 {
  "id": 20,
  "name": "AITO M7",
  "trim": "Ultra",
  "type": "hybrid",
  "fuel": "Гибрид",
  "batteryCapacity": "42 кВт·ч",
  "horsepower": "272 л.с.",
  "rangeCltc": 1300,
  "power": "42 кВт·ч",
  "drive": "RWD",
  "year": "2024",
  "mileage": null,
  "price": null,
  "image": "hybrid/aito-m7/01.webp",
  "photos": [
   "hybrid/aito-m7/01.webp",
   "hybrid/aito-m7/02.webp",
   "hybrid/aito-m7/03.webp",
   "hybrid/aito-m7/04.webp",
   "hybrid/aito-m7/05.webp",
   "hybrid/aito-m7/06.webp",
   "hybrid/aito-m7/07.webp",
   "hybrid/aito-m7/08.webp",
   "hybrid/aito-m7/09.webp"
  ],
  "exteriorCount": 5
 },
 {
  "id": 21,
  "name": "Avatr 12",
  "trim": "Max",
  "type": "hybrid",
  "fuel": "Гибрид",
  "batteryCapacity": "39.05 кВт·ч",
  "horsepower": "314 л.с.",
  "rangeCltc": 1155,
  "power": "39.05 кВт·ч",
  "drive": "RWD",
  "year": "2025",
  "mileage": null,
  "price": null,
  "image": "hybrid/avatr-12/01.webp",
  "photos": [
   "hybrid/avatr-12/01.webp",
   "hybrid/avatr-12/02.webp",
   "hybrid/avatr-12/03.webp",
   "hybrid/avatr-12/04.webp",
   "hybrid/avatr-12/05.webp",
   "hybrid/avatr-12/06.webp",
   "hybrid/avatr-12/07.webp",
   "hybrid/avatr-12/08.webp"
  ],
  "exteriorCount": 5
 },
 {
  "id": 22,
  "name": "Leapmotor C16",
  "trim": "LiDAR Premium Edition 6-Seater",
  "type": "hybrid",
  "fuel": "Гибрид",
  "batteryCapacity": "38.7 кВт·ч",
  "horsepower": "231 л.с.",
  "rangeCltc": 1150,
  "power": "38.7 кВт·ч",
  "drive": "RWD",
  "year": "2025",
  "mileage": null,
  "price": null,
  "image": "hybrid/leapmotor-c16/01.webp",
  "photos": [
   "hybrid/leapmotor-c16/01.webp",
   "hybrid/leapmotor-c16/02.webp",
   "hybrid/leapmotor-c16/03.webp",
   "hybrid/leapmotor-c16/04.webp",
   "hybrid/leapmotor-c16/05.webp",
   "hybrid/leapmotor-c16/06.webp",
   "hybrid/leapmotor-c16/07.webp",
   "hybrid/leapmotor-c16/08.webp",
   "hybrid/leapmotor-c16/09.webp"
  ],
  "exteriorCount": 5
 },
 {
  "id": 23,
  "name": "VOYAH FREE",
  "trim": "Qiankun Edition",
  "type": "hybrid",
  "fuel": "Гибрид",
  "batteryCapacity": "45 кВт·ч",
  "horsepower": "292 л.с.",
  "rangeCltc": 1458,
  "power": "45 кВт·ч",
  "drive": "RWD",
  "year": "2025",
  "mileage": null,
  "price": null,
  "image": "hybrid/voyah-free/01.webp",
  "photos": [
   "hybrid/voyah-free/01.webp",
   "hybrid/voyah-free/02.webp",
   "hybrid/voyah-free/03.webp",
   "hybrid/voyah-free/04.webp",
   "hybrid/voyah-free/05.webp",
   "hybrid/voyah-free/06.webp",
   "hybrid/voyah-free/07.webp",
   "hybrid/voyah-free/08.webp"
  ],
  "exteriorCount": 5
 },
 {
  "id": 24,
  "name": "Li Auto L9",
  "trim": "",
  "type": "hybrid",
  "fuel": "Гибрид",
  "batteryCapacity": "52.3 кВт·ч",
  "horsepower": "449 л.с.",
  "rangeCltc": 1412,
  "power": "52.3 кВт·ч",
  "drive": "AWD",
  "year": "2025",
  "mileage": null,
  "price": null,
  "image": "hybrid/li-l9/01.webp",
  "photos": [
   "hybrid/li-l9/01.webp",
   "hybrid/li-l9/02.webp",
   "hybrid/li-l9/03.webp",
   "hybrid/li-l9/04.webp",
   "hybrid/li-l9/05.webp",
   "hybrid/li-l9/06.webp",
   "hybrid/li-l9/07.webp",
   "hybrid/li-l9/08.webp",
   "hybrid/li-l9/09.webp"
  ],
  "exteriorCount": 5
 }
];
